public class PostalCodeClass {

    public results[] results;
   

       

       public class results {
            public String Name;	//Agasti SSK 
            public String BranchType;	//Branch Post Office
            public String DeliveryStatus;	//Delivery
            public String Circle;	//Maharashtra
            public String District;	//Ahmed Nagar
            public String Division;	//Shrirampur
            public String Region;	//Pune
            public String Block;	//Akole
            public String State;	//Maharashtra
            public String Country;	//India
            public String Pincode;	//422601
        }

    }


